require('robin.plugins')
require('robin.lsp')
require('robin.lualine')
require('robin.telescope')
require('robin.treesitter')
require('robin.completion')
-- require('robin.spaceline')
require('robin.nvim-autopairs')
require('robin.diffview')
