autoload -U colors && colors
autoload -Uz compinit && compinit -u -d $ZSH_CACHE/zcompdump
autoload -U promptinit; promptinit

# [ -d "$ZGEN_DIR" ] || git clone https://github.com/tarjoilija/zgen "$ZGEN_DIR"
# source $ZGEN_SOURCE
# if ! zgen saved; then
#   # echo "Initializing zgen"
#   # zgen load hlissner/zsh-autopair autopair.zsh
#   # zgen load zsh-users/zsh-history-substring-search
#   # zgen load zdharma-continuum/history-search-multi-word
#   # zgen load zsh-users/zsh-completions src
#   # zgen load junegunn/fzf shell
#   # zgen load zsh-users/zsh-autosuggestions
#   # [ -z "$SSH_CONNECTION" ] && zgen load zdharma-continuum/fast-syntax-highlighting
#   zgen save
# fi

# plugins
source $ZDOTDIR/zsh-autopair/zsh-autopair.zsh
source $ZDOTDIR/zsh-history-substring-search/zsh-history-substring-search.zsh
source $ZDOTDIR/zsh-history-search-multi-word/zsh-history-search-multi-word.plugin.zsh
source $ZDOTDIR/zsh-completions/zsh-completions.plugin.zsh
source $ZDOTDIR/fzf/shell/completion.zsh
source $ZDOTDIR/fzf/shell/key-bindings.zsh
source $ZDOTDIR/zsh-autosuggestions/zsh-autosuggestions.zsh
[ -z "$SSH_CONNECTION" ] && source $ZDOTDIR/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh

# config stuff
source $ZDOTDIR/config.zsh
source $ZDOTDIR/keybinds.zsh
source $ZDOTDIR/completion.zsh
source $ZDOTDIR/aliases.zsh

# cache function
function _cache {
  command -v "$1" >/dev/null || return 1
  local cache_dir="$XDG_CACHE_HOME/${SHELL##*/}"
  local cache="$cache_dir/$1"
  if [[ ! -f $cache || ! -s $cache ]]; then
    echo "Caching $1"
    mkdir -p $cache_dir
    "$@" >$cache
  fi
  source $cache || rm -f $cache
}
_cache fasd --init posix-alias zsh-{hook,{c,w}comp{,-install}}

# auto pair
autopair-init

# fd > find
if command -v fd >/dev/null; then
  export FZF_DEFAULT_OPTS="--reverse --ansi"
  export FZF_DEFAULT_COMMAND="fd ."
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
  export FZF_ALT_C_COMMAND="fd -t d . $HOME"
fi

## Auto-generated by my nix config
source $ZDOTDIR/extra.zshrc

# Source fzf.zsh when it is available
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# If you have host-local configuration, this is where you'd put it
[ -f ~/.zshrc ] && source ~/.zshrc

# Load asdf when available
[ -d ~/.asdf ] && . $HOME/.asdf/asdf.sh
